version: '3'
services:

  db:
    image: mariadb:10.5.8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: star_wars
      MYSQL_USER: go_test
      MYSQL_PASSWORD: star_wars123
    command: --init-file /data/application/init.sql
    volumes:
      - db-data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./init.sql:/data/application/init.sql
    ports:
      - 3306:3306

volumes:
  db-data:
    driver: local