basePath: /api
definitions:
  errors_handler.ErrorsResponse:
    properties:
      message:
        type: string
    type: object
  generic.Pagination:
    properties:
      count:
        type: integer
      next_page:
        type: integer
      previous_page:
        type: integer
    type: object
  planet.Film:
    properties:
      created_at:
        type: string
      director:
        type: string
      id:
        type: integer
      name:
        type: string
      release_date:
        type: string
    type: object
  planet.PlanetDB:
    properties:
      climate:
        type: string
      created_at:
        type: string
      deleted_at:
        type: string
      films:
        items:
          $ref: '#/definitions/planet.Film'
        type: array
      id:
        type: integer
      name:
        type: string
      terrain:
        type: string
    type: object
  planet.ResponsePlanets:
    properties:
      data:
        items:
          $ref: '#/definitions/planet.PlanetDB'
        type: array
      pagination:
        $ref: '#/definitions/generic.Pagination'
    type: object
info:
  contact: {}
  title: Star Wars API
  version: "1.0"
paths:
  /planets:
    get:
      consumes:
      - application/json
      description: get planets
      parameters:
      - description: page
        in: query
        name: page
        type: integer
      - description: limit
        in: query
        name: limit
        type: integer
      - description: name
        in: query
        name: name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/planet.ResponsePlanets'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors_handler.ErrorsResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/errors_handler.ErrorsResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors_handler.ErrorsResponse'
      summary: List planets
      tags:
      - planets
  /planets/{id}:
    delete:
      consumes:
      - application/json
      description: delete planet by ID
      parameters:
      - description: Planet ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors_handler.ErrorsResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/errors_handler.ErrorsResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors_handler.ErrorsResponse'
      summary: Delete a planet
      tags:
      - planets
    get:
      consumes:
      - application/json
      description: get planet by ID
      parameters:
      - description: Planet ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/planet.PlanetDB'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors_handler.ErrorsResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/errors_handler.ErrorsResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors_handler.ErrorsResponse'
      summary: Show a planet
      tags:
      - planets
swagger: "2.0"
