definitions:
  errors_handler.ErrorsResponse:
    properties:
      message:
        type: string
    type: object
  generic.Pagination:
    properties:
      count:
        type: integer
      next_page:
        type: integer
      previous_page:
        type: integer
    type: object
  product.ProductDB:
    properties:
      created_at:
        type: string
      deleted_at:
        type: string
      id:
        type: integer
      name:
        type: string
      quantity:
        type: integer
    required:
    - name
    - quantity
    type: object
  product.ResponseProducts:
    properties:
      data:
        items:
          $ref: '#/definitions/product.ProductDB'
        type: array
      pagination:
        $ref: '#/definitions/generic.Pagination'
    type: object
info:
  contact: {}
paths:
  /api/products:
    get:
      consumes:
      - application/json
      description: get products
      parameters:
      - description: page
        in: query
        name: page
        type: integer
      - description: limit
        in: query
        name: limit
        type: integer
      - description: name
        in: query
        name: name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/product.ResponseProducts'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors_handler.ErrorsResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/errors_handler.ErrorsResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors_handler.ErrorsResponse'
      summary: List products
      tags:
      - products
    post:
      consumes:
      - application/json
      description: Endpoint to create products
      parameters:
      - description: Request Product
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/product.ProductDB'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/product.ProductDB'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors_handler.ErrorsResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/errors_handler.ErrorsResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors_handler.ErrorsResponse'
      summary: Endpoint to create products
      tags:
      - products
  /api/products/{id}:
    delete:
      consumes:
      - application/json
      description: delete products by ID
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors_handler.ErrorsResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/errors_handler.ErrorsResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors_handler.ErrorsResponse'
      summary: Delete a products
      tags:
      - products
    get:
      consumes:
      - application/json
      description: get product by ID
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/product.ProductDB'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors_handler.ErrorsResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/errors_handler.ErrorsResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors_handler.ErrorsResponse'
      summary: Show a product
      tags:
      - products
    put:
      consumes:
      - application/json
      description: Endpoint to update products
      parameters:
      - description: Request Product
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/product.ProductDB'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/product.ProductDB'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors_handler.ErrorsResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/errors_handler.ErrorsResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors_handler.ErrorsResponse'
      summary: Endpoint to update products
      tags:
      - products
swagger: "2.0"
